/*
 * Copyright (C) 2014 router
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package medx;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author router
 */
public class AdminPanel extends stdpanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel( JPanel j ) {
        super( j );
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        AddPatientbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        delDocButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        addNewDrugButton = new javax.swing.JButton();
        delDrugButton = new javax.swing.JButton();

        jButton1.setText("Add  New Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AddPatientbutton.setText("Add  New Patient");
        AddPatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientbuttonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        delDocButton.setText("Delete a  Doctor");
        delDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDocButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Delete a patient");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        addNewDrugButton.setText("Add a Drug");
        addNewDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDrugButtonActionPerformed(evt);
            }
        });

        delDrugButton.setText("Delete a Drug");
        delDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDrugButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewDrugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPatientbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delDrugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(282, 282, 282))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delDocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPatientbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delDrugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewDrugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewDoctorPanel d1 = new NewDoctorPanel(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
        JDBCConnections j1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            WelcomePanel a1 = new WelcomePanel(j1);
            j1.removeAll();
            j1.add(a1,BorderLayout.NORTH);
            j1.repaint();
            j1.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDocButtonActionPerformed
        // TODO add your handling code here:
        DeleteDoctorSearchPanel d1 = new DeleteDoctorSearchPanel(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
    }//GEN-LAST:event_delDocButtonActionPerformed

    private void AddPatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientbuttonActionPerformed
        // TODO add your handling code here:
        NewPatientPanel d1 = new NewPatientPanel(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
        JDBCConnections j1;
    }//GEN-LAST:event_AddPatientbuttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PatientView d1 = new PatientView(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addNewDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDrugButtonActionPerformed
        // TODO add your handling code here:
        PharmacistNewDrug d1 = new PharmacistNewDrug(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
    }//GEN-LAST:event_addNewDrugButtonActionPerformed

    private void delDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDrugButtonActionPerformed
        // TODO add your handling code here:
        DrugView d1 = new DrugView(j1);
        j1.removeAll();
        j1.add(d1);
        j1.revalidate();
    }//GEN-LAST:event_delDrugButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientbutton;
    private javax.swing.JButton addNewDrugButton;
    private javax.swing.JButton delDocButton;
    private javax.swing.JButton delDrugButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
