/*
 * Copyright (C) 2014 router
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package medx;

import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author router
 */
public class DoctorPanel extends stdpanel {
    String DoctorName;
    Integer DoctorAge;
    String DoctorGender;
    String DoctorAddressLine1;
    String DoctorAddressLine2;
    Integer DoctorPhone;
    Integer DoctorJoiningYear;
    String DoctorDepartment;
    Integer DoctorId;
    Integer CurrentAppoinmentId;

    /**
     * Creates new form NewDoctorPanel
     */
    public static ResultSet queryResult;
    public DoctorPanel( JPanel j, ResultSet rs ) {
        super( j );
        queryResult = rs;
        initComponents();
        try {
            docId.setText( rs.getString("d_id") );
            docName.setText( rs.getString("d_name") );
            DoctorId = Integer.parseInt( rs.getString("d_id") );
        } catch ( Exception e ) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        docName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        docId = new javax.swing.JTextField();
        viewQueueButton = new javax.swing.JButton();
        patientComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        drugCombo1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        drugCombo2 = new javax.swing.JComboBox();
        drugQty1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        drugQty2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        drugCombo3 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        drugQty3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        drugCombo4 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        drugQty4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentRemarks = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        appoinmentId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setText("Doctor Name ");

        docName.setEditable(false);

        jLabel9.setText("Doctor Id ");

        docId.setEditable(false);

        viewQueueButton.setText("View Queue");
        viewQueueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQueueButtonActionPerformed(evt);
            }
        });

        patientComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Treat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Patient Age");

        jLabel3.setText("Patient Gender");

        jTextField2.setEditable(false);

        jLabel4.setText("Drug 1");

        drugCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCombo1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Drug 2");

        drugQty1.setEditable(false);
        drugQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugQty1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Qty");

        jLabel7.setText("Qty");

        drugQty2.setEditable(false);

        jLabel8.setText("Drug 3");

        jLabel10.setText("Qty");

        drugQty3.setEditable(false);

        jLabel11.setText("Drug 4");

        jLabel12.setText("Qty");

        drugQty4.setEditable(false);
        drugQty4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugQty4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Remarks");

        treatmentRemarks.setEditable(false);
        treatmentRemarks.setColumns(20);
        treatmentRemarks.setRows(5);
        jScrollPane1.setViewportView(treatmentRemarks);

        jButton3.setText("Treatment Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setText("Appoinment Id");

        appoinmentId.setEditable(false);

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewQueueButton)
                            .addGap(28, 28, 28)
                            .addComponent(patientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(4, 4, 4)
                            .addComponent(docName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(appoinmentId))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(docId, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(drugCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(drugCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(drugCombo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(drugCombo4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(drugQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(drugQty2)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(drugQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(drugQty4))))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)))
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(docName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(docId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewQueueButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(drugCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(drugQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appoinmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(drugQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(drugCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugQty4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(drugCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewQueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQueueButtonActionPerformed
        // TODO add your handling code here:
        try {
            JDBCConnections j1 = new JDBCConnections();
            String[] PatientNames = j1.getPatientNames( this.DoctorId );
            patientComboBox.removeAllItems();
            DefaultComboBoxModel PatientListModel = new DefaultComboBoxModel(PatientNames);
            patientComboBox.setModel( PatientListModel );
            ResultSet rs = j1.selectParticularPatient( patientComboBox.getSelectedItem().toString() );
            jTextField1.setText( rs.getString( "p_id" ) );
            jTextField2.setText( rs.getString( "p_gender" ) );
            CurrentAppoinmentId = j1.getAppoinmentId( DoctorId, rs.getInt( "p_id" )  );        
            appoinmentId.setText( CurrentAppoinmentId.toString() );
        }catch ( Exception e ) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewQueueButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          DoctorView d1 = new DoctorView(j1);
            j1.removeAll();
            j1.add(d1);
            j1.repaint();
            j1.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void drugQty4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugQty4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugQty4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JDBCConnections j1 = new JDBCConnections();
        if ( treatmentRemarks.getText() != "" ) {
            j1.createTreatmentRemarks( this.CurrentAppoinmentId, this.treatmentRemarks.getText() );
        }
        if( drugCombo1.getSelectedIndex() == -1  ) {
            Integer selectedDrugId = j1.getDrugId( this.drugCombo1.getSelectedItem().toString() );
            j1.createTreatmentDrugDetails( this.CurrentAppoinmentId, selectedDrugId, Integer.parseInt( this.drugQty1.getText() ) );
        }
        if( drugCombo2.getSelectedIndex() == -1 ) {
            Integer selectedDrugId = j1.getDrugId( this.drugCombo2.getSelectedItem().toString() );
            j1.createTreatmentDrugDetails( this.CurrentAppoinmentId, selectedDrugId, Integer.parseInt( this.drugQty2.getText() ) );
        } 
        if( drugCombo3.getSelectedIndex() == -1 ) {
            Integer selectedDrugId = j1.getDrugId( this.drugCombo3.getSelectedItem().toString() );
            j1.createTreatmentDrugDetails( this.CurrentAppoinmentId, selectedDrugId, Integer.parseInt( this.drugQty3.getText() ) );
        } 
        if( drugCombo4.getSelectedIndex() == -1 ) {
            Integer selectedDrugId = j1.getDrugId( this.drugCombo4.getSelectedItem().toString() );
            j1.createTreatmentDrugDetails( this.CurrentAppoinmentId, selectedDrugId, Integer.parseInt( this.drugQty4.getText() ) );
        }
        j1.treatmentDone( this.CurrentAppoinmentId );
        JOptionPane.showMessageDialog(null,"Successfully Added","Treatment Details Updated",JOptionPane.WARNING_MESSAGE);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void drugQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugQty1ActionPerformed

    private void patientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientComboBoxActionPerformed
        // TODO add your handling code here:
        try {
            JDBCConnections jdbcConn = new JDBCConnections();
            ResultSet rs = jdbcConn.selectParticularPatient( patientComboBox.getSelectedItem().toString() );
            jTextField1.setText( rs.getString( "p_age" ) );
            jTextField2.setText( rs.getString( "p_gender" ) );
            Integer CurrentAppoinmentId = jdbcConn.getAppoinmentId( DoctorId, rs.getInt( "p_id" )  );        
            appoinmentId.setText( CurrentAppoinmentId.toString() );

        } catch ( Exception e ) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_patientComboBoxActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.drugQty1.setEditable(true);
        this.drugQty2.setEditable(true);
        this.drugQty3.setEditable(true);
        this.drugQty4.setEditable(true);
        this.treatmentRemarks.setEditable(true);
        try {
            JDBCConnections j1 = new JDBCConnections();
            String[] DrugNames = j1.getDrugNames();
            drugCombo1.removeAllItems();
            drugCombo2.removeAllItems();
            drugCombo3.removeAllItems();
            drugCombo4.removeAllItems();
            
            DefaultComboBoxModel DrugListModel1 = new DefaultComboBoxModel(DrugNames);
            DefaultComboBoxModel DrugListModel2 = new DefaultComboBoxModel(DrugNames);
            DefaultComboBoxModel DrugListModel3 = new DefaultComboBoxModel(DrugNames);
            DefaultComboBoxModel DrugListModel4 = new DefaultComboBoxModel(DrugNames);
            drugCombo1.setModel( DrugListModel1 );
            drugCombo2.setModel( DrugListModel2 );
            drugCombo3.setModel( DrugListModel3 );
            drugCombo4.setModel( DrugListModel4 );
            drugCombo1.insertItemAt("", 0);
            drugCombo2.insertItemAt("", 0);
            drugCombo3.insertItemAt("", 0);
            drugCombo4.insertItemAt("", 0);
            drugCombo1.setSelectedIndex(0);
            drugCombo2.setSelectedIndex(0);
            drugCombo3.setSelectedIndex(0);
            drugCombo4.setSelectedIndex(0);
        }catch ( Exception e ) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void drugCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugCombo1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.patientComboBox.setSelectedIndex( this.patientComboBox.getSelectedIndex()+ 1 );
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appoinmentId;
    public javax.swing.JTextField docId;
    private javax.swing.JTextField docName;
    private javax.swing.JComboBox drugCombo1;
    private javax.swing.JComboBox drugCombo2;
    private javax.swing.JComboBox drugCombo3;
    private javax.swing.JComboBox drugCombo4;
    private javax.swing.JTextField drugQty1;
    private javax.swing.JTextField drugQty2;
    private javax.swing.JTextField drugQty3;
    private javax.swing.JTextField drugQty4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox patientComboBox;
    private javax.swing.JTextArea treatmentRemarks;
    private javax.swing.JButton viewQueueButton;
    // End of variables declaration//GEN-END:variables
}
